// Simple billing module generated by CommandOS Relay.
export function calculateInvoice(items, taxRate = 0) {
  if (!Array.isArray(items)) throw new TypeError('items must be an array');
  const subtotal = items.reduce((sum, i) => sum + Number(i.price) * Number(i.qty), 0);
  const round = (n) => Math.round(n * 100) / 100;
  const tax = round(subtotal * taxRate);
  return { subtotal: round(subtotal), tax, total: round(subtotal + tax) };
}

export function applyDiscount(total, percent = 0) {
  if (percent < 0 || percent > 100) throw new RangeError('percent out of range');
  return Math.round(total * (1 - percent / 100) * 100) / 100;
}